---
# Add python3.6
- name: add repository for python 3.6
  become: true
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: install python 3.6
  become: true
  apt:
    name:
      - python3.6
      - python3.6-dev
    update_cache: true
  register: python_install

# - name: install pip3.6
#   become: true
#   command: curl https://bootstrap.pypa.io/get-pip.py | python3.6
#   when: python_install.changed
