---
- hosts: all

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  vars:
    - nodejs_install_npm_user: ubuntu

  roles:
    - role: "marvel-nccr.invenio_bootcamp"
